export const interviewSchema = {
  name: "Interview",
  schema: {
    title: "Interview Stage",
    description: "Schedule and configure an interview round for the candidate.",
    fields: [
      {
        key: "round_name",
        type: "text",
        label: "Round Name",
        placeholder: "e.g., Technical Round 1",
        order: 1,
        default: "",
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "round_type",
        type: "dropdown",
        label: "Round Type",
        placeholder: "Select round type",
        order: 2,
        default: null,
        required: true,
        readonly: false,
        options: [
          { label: "Screening Call", value: "screening" },
          { label: "Technical", value: "technical" },
          { label: "System Design", value: "system_design" },
          { label: "HR / Culture Fit", value: "hr" },
          { label: "Managerial", value: "managerial" },
          { label: "Assignment / Take-Home", value: "assignment" },
          { label: "Final / Offer Discussion", value: "final" },
        ],
        validation: {},
      },
      {
        key: "interview_format",
        type: "dropdown",
        label: "Interview Format",
        placeholder: "Select format",
        order: 3,
        default: null,
        required: false,
        readonly: false,
        options: [
          { label: "Video Call", value: "video" },
          { label: "Phone Call", value: "phone" },
          { label: "In-Person (F2F)", value: "in_person" },
          { label: "Panel Interview", value: "panel" },
          { label: "Group Discussion", value: "group" },
        ],
        validation: {},
      },
      {
        key: "interviewer_name",
        type: "text",
        label: "Interviewer Name",
        placeholder: "Enter interviewer's name",
        order: 4,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "interviewer_designation",
        type: "text",
        label: "Interviewer Designation",
        placeholder: "e.g., Engineering Manager",
        order: 5,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "scheduled_date",
        type: "date",
        label: "Scheduled Date",
        placeholder: "Select date",
        order: 6,
        default: null,
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "duration_minutes",
        type: "number",
        label: "Duration (minutes)",
        placeholder: "e.g., 60",
        order: 7,
        default: 60,
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "meeting_link",
        type: "text",
        label: "Meeting Link / Venue",
        placeholder: "e.g., meet.google.com/xxx or Office Room 3B",
        order: 8,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "outcome",
        type: "dropdown",
        label: "Interview Outcome",
        placeholder: "Select outcome",
        order: 9,
        default: null,
        required: false,
        readonly: false,
        options: [
          { label: "Pending", value: "pending" },
          { label: "Selected", value: "selected" },
          { label: "On Hold", value: "on_hold" },
          { label: "Rejected", value: "rejected" },
          { label: "No Show", value: "no_show" },
        ],
        validation: {},
      },
      {
        key: "feedback",
        type: "textarea",
        label: "Interviewer Feedback",
        placeholder: "Provide detailed feedback on the candidate's performance...",
        order: 10,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "rating",
        type: "dropdown",
        label: "Overall Rating",
        placeholder: "Select rating",
        order: 11,
        default: null,
        required: false,
        readonly: false,
        options: [
          { label: "★★★★★ Exceptional", value: "5" },
          { label: "★★★★  Strong", value: "4" },
          { label: "★★★   Average", value: "3" },
          { label: "★★    Below Average", value: "2" },
          { label: "★     Poor", value: "1" },
        ],
        validation: {},
      },
    ],
  },
};
