export const jdSchema = {
  name: "Job Description",
  schema: {
    title: "Job Description",
    description: "Define the role, responsibilities, qualifications, and skills required for the position.",
    fields: [
      {
        key: "role_title",
        type: "text",
        label: "Role Title",
        placeholder: "e.g., Senior Data Analyst",
        order: 1,
        default: "",
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "role_summary",
        type: "textarea",
        label: "Role Summary",
        placeholder: "Brief overview of the role and its purpose in the organisation...",
        order: 2,
        default: "",
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "key_responsibilities",
        type: "textarea",
        label: "Key Responsibilities",
        placeholder: "List the main duties and responsibilities...",
        order: 3,
        default: "",
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "min_experience_years",
        type: "number",
        label: "Minimum Experience (Years)",
        placeholder: "e.g., 3",
        order: 4,
        default: null,
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "max_experience_years",
        type: "number",
        label: "Maximum Experience (Years)",
        placeholder: "e.g., 7",
        order: 5,
        default: null,
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "education_qualification",
        type: "dropdown",
        label: "Minimum Education",
        placeholder: "Select qualification",
        order: 6,
        default: null,
        required: false,
        readonly: false,
        options: [
          { label: "High School / 12th Pass", value: "high_school" },
          { label: "Diploma", value: "diploma" },
          { label: "Bachelor's Degree", value: "bachelors" },
          { label: "Master's Degree", value: "masters" },
          { label: "MBA", value: "mba" },
          { label: "PhD", value: "phd" },
        ],
        validation: {},
      },
      {
        key: "technical_skills",
        type: "textarea",
        label: "Technical Skills Required",
        placeholder: "e.g., Python, SQL, Tableau, AWS...",
        order: 7,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "soft_skills",
        type: "textarea",
        label: "Soft Skills",
        placeholder: "e.g., Communication, Leadership, Problem-solving...",
        order: 8,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "employment_type",
        type: "dropdown",
        label: "Employment Type",
        placeholder: "Select type",
        order: 9,
        default: null,
        required: false,
        readonly: false,
        options: [
          { label: "Full-Time", value: "full_time" },
          { label: "Part-Time", value: "part_time" },
          { label: "Contract", value: "contract" },
          { label: "Freelance", value: "freelance" },
        ],
        validation: {},
      },
      {
        key: "salary_range",
        type: "text",
        label: "Salary Range (CTC)",
        placeholder: "e.g., ₹8L – ₹12L per annum",
        order: 10,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "benefits",
        type: "textarea",
        label: "Benefits & Perks",
        placeholder: "e.g., Health insurance, ESOP, Flexible hours...",
        order: 11,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "jd_status",
        type: "dropdown",
        label: "JD Status",
        placeholder: "Select status",
        order: 12,
        default: "draft",
        required: false,
        readonly: false,
        options: [
          { label: "Draft", value: "draft" },
          { label: "Under Review", value: "review" },
          { label: "Approved", value: "approved" },
          { label: "Published", value: "published" },
        ],
        validation: {},
      },
    ],
  },
};
