export const requisitionSchema = {
  name: "Requisition",
  schema: {
    title: "Job Requisition",
    description: "Details about the open position and hiring requirements.",
    fields: [
      {
        key: "job_title",
        type: "text",
        label: "Job Title",
        placeholder: "e.g., Senior Software Engineer",
        order: 1,
        default: "",
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "department",
        type: "text",
        label: "Department",
        placeholder: "e.g., Engineering",
        order: 2,
        default: "",
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "hiring_manager",
        type: "text",
        label: "Hiring Manager",
        placeholder: "Enter hiring manager name",
        order: 3,
        default: "",
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "position_type",
        type: "dropdown",
        label: "Position Type",
        placeholder: "Select type",
        order: 4,
        default: null,
        required: true,
        readonly: false,
        options: [
          { label: "Full-Time", value: "full_time" },
          { label: "Part-Time", value: "part_time" },
          { label: "Contract", value: "contract" },
          { label: "Internship", value: "internship" },
        ],
        validation: {},
      },
      {
        key: "number_of_positions",
        type: "number",
        label: "Number of Positions",
        placeholder: "e.g., 2",
        order: 5,
        default: 1,
        required: true,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "budget_range",
        type: "text",
        label: "Budget Range (CTC)",
        placeholder: "e.g., ₹12L – ₹18L",
        order: 6,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "location",
        type: "text",
        label: "Work Location",
        placeholder: "e.g., Bengaluru / Remote",
        order: 7,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "work_mode",
        type: "dropdown",
        label: "Work Mode",
        placeholder: "Select mode",
        order: 8,
        default: null,
        required: false,
        readonly: false,
        options: [
          { label: "On-site", value: "on_site" },
          { label: "Hybrid", value: "hybrid" },
          { label: "Remote", value: "remote" },
        ],
        validation: {},
      },
      {
        key: "priority",
        type: "dropdown",
        label: "Hiring Priority",
        placeholder: "Select priority",
        order: 9,
        default: "medium",
        required: false,
        readonly: false,
        options: [
          { label: "Critical", value: "critical" },
          { label: "High", value: "high" },
          { label: "Medium", value: "medium" },
          { label: "Low", value: "low" },
        ],
        validation: {},
      },
      {
        key: "target_start_date",
        type: "date",
        label: "Target Start Date",
        placeholder: "Select date",
        order: 10,
        default: null,
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
      {
        key: "justification",
        type: "textarea",
        label: "Business Justification",
        placeholder: "Why is this role needed?",
        order: 11,
        default: "",
        required: false,
        readonly: false,
        options: [],
        validation: {},
      },
    ],
  },
};
